FROM python:3.9

LABEL version="1.0"
LABEL description="Dockerfile for postgresql Conn App"

WORKDIR /app

COPY requirements.txt requirements.txt
COPY main.py main.py

ENV POSTGRES_HOST, POSTGRES_PORT, POSTGRES_DB, POSTGRES_USER, POSTGRES_PASSWORD


RUN pip install --no-cache-dir -r requirements.txt

ENTRYPOINT [ "python" ]
CMD ["main.py"] 