services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=12345
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    depends_on:
      - mongodb
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=12345
      - ME_CONFIG_MONGODB_SERVER=mongodb
    ports:
      - "8081:8081"

  mongo_app:
    image: mongo_app:latest
    container_name: mongo_app
    environment:
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_DB: mongodb
      MONGO_USER: root
      MONGO_PASSWORD: 12345
    depends_on:
      - mongodb

volumes:
  mongodb_data:
